puppetlabs/puppetlabs-wsus_client

README.md
Replaces #17 which was from abandoned fork.
=> (docs) Readme updates

.gitignore, .sync.yml, .travis.yml, Gemfile, appveyor.yml
This ensures the following items are under moduleysnc:
* .gitignore
* .travis.yml
* CONTRIBUTING.md
* Gemfile
* appveyor.yml
* spec/spec.opts
Most importantly, this ensures that acl has up to date Gemfile, Travis
CI and AppVeyor configurations that allow it to be tested properly.
=> (MODULES-2207) Update Modulesync

README.md
- Use updated style readme style
- Change from ``` to ~~~ and include the language in the markdown
- Update to new standard for classes and parameters
- Change to new style which uses newline for description and changes markedown
from * to #### on the paramter name line
- Whitespace and format changes
- Updates the `enable_status_server` description
- Add additional info about what it is doing under the hood
- Add setup description block including install process
=> (doc) Prepare documentation for supported release

README.md
Revises the pre-docs to conform to Forge README styles.
Also:
- Added the Developments section.
- Noted Group Policy conflicts.
- Revised the `server_url` parameter description to more closely 
reflect code behavior.
=> (docs) Revise pre-docs.

spec/spec_helper_acceptance.rb
The pre-suite needs to be updated to allow for installing the module from
the Forge.
[skip ci]
=> (FM-5061) Update Acceptance Pre-suite

.sync.yml, CONTRIBUTING.md, Gemfile, LICENSE, MAINTAINERS.md, NOTICE, appveyor.yml
The PR contains the updates from the new modsync config for windows;
- LICENSE, NOTICE, CONTRIBUTING, MAINTAINERS updates (where applicable)
- Gemfile, Appveyor, Travis, gitignore cleanup
https://github.com/puppetlabs/modulesync_configs/pull/66
https://github.com/puppetlabs/modulesync_configs/pull/63
https://github.com/puppetlabs/modulesync_configs/pull/62
https://github.com/puppetlabs/modulesync_configs/pull/61
=> (maint) modsync update - stable

CHANGELOG.md, metadata.json
- Fix links and dependencies in metadata.json
- Fix acceptance tests
=> (FM-5144) Release 1.0.2

metadata.json
This commit updates the compatiblity for latest PE version (2016.4.0)
=> (FM-5144) Update metadata for latest PE version

CHANGELOG.md, metadata.json
In preparation for 1.0.2 release master is merged down to stable.
=> (maint) Merge branch 'master' into stable

.gitignore, .sync.yml, Gemfile, Rakefile
Merge down from stable to master
=> Merge stable to master

Gemfile
Module updated with lastest modsync settings
=> (MODULES-3536) modsync update

CHANGELOG.md, metadata.json
This commit prepares the module for a version 1.1.0 release.
=> (MODULES-8115) Prep for v1.1.0 release

CHANGELOG.md
This commit updates the changelog with the correct Jira Ticket number for the
PowerShell task.
=> (maint) Update changelog with correct Jira Ticket

CHANGELOG.md, metadata.json
This commit merges the 1.1.0 release back into master.
=> (MODULES-8119) Mergeback release into master

README.md
=> MODULES-9419 - Add Module Contribution Guide Section

metadata.json
=> MODULES-9414 - Update puppet minimum version and fix stdlib upper limit

spec/classes/init_spec.rb
removed accept_trusted_publisher_certs test. It was duplicated
=> MODULES-9411 - Unit tests & Acceptance tests Validation

.travis.yml
Execute acceptance tests on Travis and/or Appveyor
=> MODULES-9418 Execute acceptance tests on Travis and/or Appveyor

.gitignore, .pdkignore, .puppet-lint.rc, .rubocop.yml, .sync.yml, Gemfile, Rakefile, appveyor.yml, lib/puppet/parser/functions/parse_auto_update_option.rb, lib/puppet/parser/functions/parse_scheduled_install_day.rb, lib/puppet/parser/functions/validate_in_range.rb, manifests/init.pp, metadata.json, spec/acceptance/wsus_client_spec.rb, spec/classes/init_spec.rb, spec/functions/parse_auto_update_option_spec.rb, spec/functions/parse_scheduled_install_day_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
➜  puppetlabs-wsus_client git:(MODULES-9412) pdk validate                                                          
pdk (INFO): Running all available validators...
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.5.0
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"]).
[✔] Checking Puppet manifest syntax (**/*.pp).
[✔] Checking Puppet manifest style (**/*.pp).
[✖] Checking Ruby code style (**/**.rb).
[✔] Checking task names (tasks/**/*).
[✔] Checking task metadata style (tasks/*.json).
pdk_version: 1.11.0
pdksync will be done by https://tickets.puppetlabs.com/browse/MODULES-9413
with new version of pdk: 1.11.1
=> Modules 9412 - pdk convert or pdk update on the module

CHANGELOG.md, metadata.json
You can check the full changelog [here](https://github.com/puppetlabs/puppetlabs-wsus_client/compare/1.1.0...caa47cf9dcd6ef1b01dffdc0008b5f8a760f9f0d)
=> MODULES-9588 - release prep 2.0.0

CHANGELOG.md, metadata.json
=> (MODULES-9589) - Release Merge back v2.0.0

.sync.yml, .travis.yml, Gemfile, Rakefile, appveyor.yml, metadata.json, spec/spec_helper.rb
"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`
=> (IAC-365) updating tokens and dataset for honeycomb

.github/pull_request_template.md, CONTRIBUTING.md, README.md
Removal of any offensive or inappropriate terminology from the code base.
=> (IAC-1019) - Removal of any Inappropriate Terminology

.github/workflows/nightly.yml, .rubocop.yml, Gemfile, Rakefile, metadata.json, spec/classes/init_spec.rb
This PR supersedes #139 as it appears as though some changes have been merged to `main` already, but there are conflicts with a number of other files that needed to be resolved.
Instead, to avoid confusion from naming, I've created a separate PR and will close #139 when this is merged.
=> (MAINT) pdk update

spec/run_pester.ps1
Pinning to pester 4 as our tests are written against this spec.
=> (maint) Pin pester version 4

.github/workflows/auto_release.yml, .github/workflows/nightly.yml, metadata.json, spec/spec_helper.rb
(MAINT) PDK update for GHA workflows + Litmus updates
pdk version: `1.18.1`
=> pdksync - (MAINT) PDK update for GHA workflows + Litmus updates

.devcontainer/README.md, .devcontainer/devcontainer.json, .github/workflows/auto_release.yml, .github/workflows/nightly.yml, .github/workflows/spec.yml, .rubocop.yml, Gemfile, Rakefile, metadata.json
pdksync_heads/main-0-gf3911d3
pdk version: `2.3.0`
=> pdksync - pdksync_heads/main-0-gf3911d3

metadata.json
SDP - I'm  unable to open a ticket... Resolving dependency graph issue(s) this morning on active engagement
=> adjusted upper limit

.github/workflows/pr_test.yml, metadata.json, spec/acceptance/wsus_client_spec.rb
Prior to this PR this module did not have any form of PR testing.
This PR aims to bring the puppetlabs-wsus_client module more inline with the rest of our modules by adding pr_test.yml github workflow.
This PR also fixes broken acceptance tests in the module.
=> (CONT-369) - add pr testing

.devcontainer/devcontainer.json, .github/workflows/auto_release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/spec.yml, Gemfile, metadata.json
PR is a result of running pdk update
=> (Maint) - PDK Update
