- Gemfile
- spec/spec_helper_acceptance.rb
- Allows us to move puppet install logic to helper gem
as well as use AIO helpers inside
> (maint) Move install to Beaker-Puppet_install_helper usage

- README.md
The variable was renamed to scheduled_install_hour at some point, the README wasn't.
> Fixed incorrect example for scheduled hour to a: work and b: make sense

- README.md
- manifests/init.pp
- spec/acceptance/wsus_client_spec.rb
- spec/classes/init_spec.rb
The max value of RebootRelaunchTimeout should be 1440(24 hours), rather than 440. I guess this miss is due to the numerical separator used in the [official document](https://technet.microsoft.com/en-us/library/dd939844%28v=ws.10%29.aspx). 
```
Range = n, where n = time in minutes (1–1,440). 
```
> (MODULES-2180) Fix the max value of RebootRelaunchTimeout

- Gemfile
Further restrict down the restrictions on windows dependencies when
using older Puppet versions, such that it works with Puppet 3.0.0 -
3.7.0. It does require a bit more logic in selecting gems but it allows
for testing older platforms without any additional known issues for
Puppet versions under 3.4.0.
> (MODULES-2207) Gem restrictions for Older puppet versions

- Gemfile
Ensure that beaker rspec is at least on a version that supports the
use of specinfra and is not known to contain bugs.
> (MODULES-2207) bin beaker-rspec to ~> 5.1

- Gemfile
Using PSH with versions lower than 0.9.0 results in issues
attempting to symlink on Windows. We'll take the latest
version as the dependency since it has the best fixes
available for cross platform testing.
> (maint) puppetlabs_spec_helper ~>0.10.3

- Gemfile
For Puppet older than 3.5.0 on Windows, a facter version at or under
1.7.5 should be selected for greatest compatibility when requesting
a gem puppet version and if a facter version has not been specified.
Update the Beaker version to use "2.20" which has an important fix for PE
installations.
> (maint) Guarantee Facter version for old Puppets / (MODULES-2452) Update beaker version

- CHANGELOG.md
- metadata.json
This also adds metadata for Puppet 2015.2 and Puppet 4.x.
> (FM-2337) Release 1.0.0 - First supported

- .gitignore
- .travis.yml
- Gemfile
- appveyor.yml
Beaker needs a version of Rake less than
11 due to using `last_comment' in
rake_task.rb:62. Reduce the version of Rake
down to the same dependency that Beaker does
as a development dependency.
Paired with Glenn Sarti <glenn.sarti at puppetlabs dot com>
> (FM-4919) update modulesync / Restrict Rake ~> 10.1

- Gemfile
During CI Triage, the WSUS Client pipeline was failing due to rspec-puppet
changing from version 2.3.2 to 2.4.0.  This commit pins rspec-puppet to
2.3.2 until the incompatibility is resolved in MODULES-3240.
> (FM-5055) Pin rspec-puppet to 2.3.2 in Gemfile

- Gemfile
- spec/functions/parse_auto_update_option_spec.rb
- spec/functions/parse_scheduled_install_day_spec.rb
Revert the explicit version pin of the rspec-puppet gem. This was introduced at commit 0daee85.
Removed creating the 'scope' variable as it is already available via rspec-puppet.  Without removing this statement, unit tests will fail on rspec-puppet 2.4.0, and probably subsequent versions as well.
> (MODULES-3240) Fix rspec-puppet incompatibility

- manifests/init.pp
- spec/classes/init_spec.rb
The AlwaysAutoRebootAtScheduledTime key allows the user to ensure
that any updates are applied on the schedule set by the user and
that the computer will restart regardless if a user is logged on
or not
> (MODULES-3016) Support AlwaysAutoRebootAtScheduledTime

- .gitignore
- .sync.yml
- Gemfile
- Rakefile
There is a known problem with specinfra versions above 2.59.0 which causes
CI failures.
https://github.com/mizzy/specinfra/pull/561
This commit pins specinfra to 2.59.0 until this is resolved
The rakefile is attempting to override the default puppet lint settings however
these settings are more permissive than the defaults and are causing false
lint failures e.g. the vendor directory is not excluded in thie Rakefile but
the puppetlabs_spec_helper does this by default.  This PR removes the
ignore_paths setting as the spec helper already does this.  Also added a comment
that the 80 and 140 char rule changes can be removed once next version of
spec_helper is released as they are already the defaults.
> (maint) Pin specinfra gem to 2.59.0

- spec/classes/init_spec.rb
Previously the verification regular expression expected a single digit as the
lower bound integer.  This is not the case as some settings could contain one
or more digits.  This commit changes the regular expression to expect one or
more digits in the error message.
> (maint) Fix shared group test 'below range'

- manifests/init.pp
- spec/classes/init_spec.rb
https://tickets.puppetlabs.com/browse/MODULES-3475
adding support for AlwaysAutoRebootAtScheduledTimeMinutes which allows to restart host immediately after installing the updates
> (MODULES-3475) Support AlwaysAutoRebootAtScheduledTimeMinutes

- manifests/init.pp
In newer Windows versions wsuaserv supports a start type of "manual (trigger
start)" which is another form of running/enabled in which the service will
start (on-demand) in response to some defined event. However, in the
wsus-client module, puppet sees this state as enabled but not running, and
starts the service with every run.  The short-term fix in this commit is to
consider the service running when enabled on these operating systems. The
long-term fix, captured by PUP-6489 may be to modify the puppet windows service
provider to support the trigger state.  It's unclear at this time whether that
effort would be justified because at this time it seems like trigger start
services are not commonplace and aren't an officially supported service type.
reference …
> (MODULES-2420) omit ensure => running due to "trigger start"

- metadata.json
to go along with modern convention and to be compatible with blacksmith, the slash needs to be replaced with a hyphen
> (maint) changes name in metadata

- metadata.json
This commit adds Server 2016 and the corresponding Windows Client versions to
the list of supported Windows OSes.
> (MODULES-4271) Add Server 2016 and client OS to metadata

- tasks/update_history.json
- tasks/update_history.ps1
This PR adds a script that will query the update history of a Windows
computer and then output that information for a bolt or PE Task.
> (MODULES-7222) Create a task to list the Update History

- metadata.json
Update gha templates
pdk version: `1.19.0.pre (47)`
> pdksync - Update gha templates

- manifests/init.pp
- manifests/setting.pp
- spec/classes/init_spec.rb
Previous to this commit, the wsus_client module would fail to start
unit and/or spec testing on any PR, crashing at the beginning of the
process and throwing syntax errors.
This commit aims to review and fix multiple syntax warnings, making sure
that the module complies with syntax standards and that each parameter
has an appropriate data type assigned.
Note: This is backwards incompatible.
> (gh-cat-9) Add specific data types

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
- Support for Windows 7 and 8 was removed.
- Support for Windows Server 2008 and 2008 R2 was removed. ﻿
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Drop support for Windows 7, 8, 2008 (Server) and 2008 R2 (Server)

- spec/classes/init_spec.rb
Prior to this PR, spec tests for this module were not as strict on error messages as was hoped due to changes introduced in https://github.com/puppetlabs/puppetlabs-wsus_client/pull/181.
This PR aims to reduce the chance of incorrect erroneous tests appearing as passed, by matching to more accurate and strict error messages.
> (CONT-192) - Stricter spec test error checking

- metadata.json
Following the last major version update for puppetlabs-registry, several modules found themselves needing a dependency update. This commit aims to adjust the registry dependency within the module so that it is compatible with registry 5.0.0 and onwards.
> (CONT-860) Update registry dependency

- manifests/init.pp
Provide a detailed description of all the changes present in this pull request.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
> Update documentation for 'auto_update_option' parameter
